const portofoliosData = [
    {id:1,img:"/images/horizontal1.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    {id:2,img:"/images/horizontal7.webp",desc:"Maecenas viverra justo in condimentum mattis. Integer fermentum interdum cursus. Phasellus dignissim, enim et iaculis sagittis, magna metus commodo dui, nec maximus augue tellus at nulla. Etiam erat massa, scelerisque eget ex vel, vestibulum porta purus. Pellentesque at lectus nibh. Nulla quis purus eget purus bibendum vehicula non sit amet sapien. Duis non vestibulum libero. Nulla at magna elementum, eleifend purus ac, finibus quam."},
    {id:3,img:"/images/vertical8.webp", desc:"Cras hendrerit lorem vitae libero finibus auctor ut ac nunc. Quisque facilisis ligula sit amet sem porta ornare. In ac dictum leo. Quisque maximus libero nec semper tempus. Mauris eleifend ex in nulla porttitor pharetra. Aliquam egestas non lorem eget ultricies. Suspendisse quis maximus ligula."},
    {id:4,img:"/images/horizontal9.webp", desc:"Proin ut ligula id elit hendrerit luctus. Ut id cursus mi. Morbi vitae congue dolor, ut suscipit dui. Pellentesque blandit turpis in dolor facilisis, ac aliquam mauris imperdiet. Fusce tristique vehicula nisi. In sagittis feugiat nisl id scelerisque. Nulla sodales lobortis posuere. Pellentesque turpis lorem"},
    {id:5,img:"/images/horizontal4.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    {id:6,img:"/images/vertical2.webp",desc:"Maecenas viverra justo in condimentum mattis. Integer fermentum interdum cursus. Phasellus dignissim, enim et iaculis sagittis, magna metus commodo dui, nec maximus augue tellus at nulla. Etiam erat massa, scelerisque eget ex vel, vestibulum porta purus. Pellentesque at lectus nibh. Nulla quis purus eget purus bibendum vehicula non sit amet sapien. Duis non vestibulum libero. Nulla at magna elementum, eleifend purus ac, finibus quam."},
    {id:7,img:"/images/horizontal5.webp", desc:"Cras hendrerit lorem vitae libero finibus auctor ut ac nunc. Quisque facilisis ligula sit amet sem porta ornare. In ac dictum leo. Quisque maximus libero nec semper tempus. Mauris eleifend ex in nulla porttitor pharetra. Aliquam egestas non lorem eget ultricies. Suspendisse quis maximus ligula."},
    {id:8,img:"/images/horizontal6.webp", desc:"Proin ut ligula id elit hendrerit luctus. Ut id cursus mi. Morbi vitae congue dolor, ut suscipit dui. Pellentesque blandit turpis in dolor facilisis, ac aliquam mauris imperdiet. Fusce tristique vehicula nisi. In sagittis feugiat nisl id scelerisque. Nulla sodales lobortis posuere. Pellentesque turpis lorem"},
    {id:9,img:"/images/vertical10.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    {id:10,img:"/images/vertical12.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    // {id:10,img:"/images/vertical12.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    // {id:10,img:"/images/vertical12.webp",desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed maximus ullamcorper erat, sed tincidunt dolor ullamcorper eget. Suspendisse potenti. Quisque maximus varius felis a convallis. Praesent aliquet arcu ac purus fringilla aliquet."},
    
];

const clientsData = [
    {id:1, img:"/images/Mirae_Asset_Sekuritas_Indo.webp"},
    {id:2, img:"/images/UOB.webp"},
    {id:3, img:"/images/Kementrian_Luar _Negeri.webp"},
    {id:4, img:"/images/Dyandra_Promosindo.webp"},
    {id:5, img:"/images/Pertamina_Geothermal_Energy.webp"},
    {id:6, img:"/images/Kementrian_Keuangan.webp"},
    {id:7, img:"/images/Kemenkes.webp"},
    {id:8, img:"/images/Oneject_Indonesia.webp"},
    {id:9, img:"/images/Kementrian_BUMN.webp"},
    {id:10, img:"/images/Bank_Bukopin.webp"},
    {id:11, img:"/images/Adhi_Karya.webp"},
    {id:12, img:"/images/CNBC_Indonesia.webp"},
    {id:13, img:"/images/KPU.webp"},
    
]

const articlesData = [
    {id:1, img:"/images/vertical11.webp", alternative:"/images/vertical7.webp", title:"Solusi penerjemahan dokumen anda.", desc:"Layanan jasa untuk membantu anda memperoleh pengesahan atau legalisasi atas semua dokumen-dokumen anda yang telah diterjemahkan di BBS Penerjemah.", full:"BBS adalah penyedia jasa yang berhubungan dengan bahasa, dalam hal ini mengkhususkan menyediakan layanan penyewaan dan penjualan peralatan Interpreting System serta layanan jasa penerjemah bahasa asing. Usaha penyedia jasa penyewaan dan penjualan alat Interpreting System kami bermula saat banyaknya permintaan klien kami yang telah lama menggunakan jasa penerjemahan kami. Sejak itu tepatnya di awal 2005, BBS menambahkan layanan jasa penyewaan dan penjualan alat interpreter. Layanan penyewaan dan penjualan peralatan Interpreting System kami berkualitas. Alat-alat interpreting system yang kami sediakan sengaja didatangkan dari luar guna memenuhi kebutuhan klien-klien kami. Tipe dan jenisnyapun berbeda-beda. Proses instalasinya sangat mudah dan sederhana. Harga yang kami tawarkan bersaing dengan kualitas perangkat yang baik. Seiring dengan perkembangan teknologi yang sedemikian cepatnya, kini telah banyak bermunculan tipe dan jenis alat-alat interpreting system yang semakin canggih. Bersamaan dengan itu pula, permintaan klien pun semakin kritis. Guna menjawab kebutuhan klien-klien kami, kami telah memperoleh LISENSI DAELER RESMI dari sebuah produsen perangkat interpreter system terkemuka di dunia. Kami juga telah mempersiapkan katalog yang berisi contoh-contoh dari alat-alat interpreter terbaru dan teranyar saat ini. Klien-klien kami dapat menentukan pilihannya dengan mudah sesuai kebutuhannya. Dengan kelengkapan peralatan interpreter system yang kami miliki, kami selalu berupaya untuk memberikan yang terbaik bagi klien-klien kami."},
    {id:2, img:"/images/article1.webp", alternative:"/images/vertical7.webp", title:"Sewa alat Interpreter yang berpengalaman.", desc:"Seiring meningkatkanya permintaan sewa alat interpreter di Jakarta, kami telah membuka cabang baru kami di Bali, Bandung, dan Bogor. Hal ini lebih memudahkan klien kami untuk dapat memenuhi kebutuhan yang terkait dengan jasa kami."},
    {id:3, img:"/images/article2.webp", alternative:"/images/vertical7.webp", title:"Sukses event anda adalah tujuan kami.", desc:"Berbagai event baik yang bersifat nasional maupun internasional telah dapat terselenggara dengan menggunakan jasa kami. Sehingga usaha di bidang jasa sewa alat interpreter atau interpreting equipment rental kami semakin dikenal."},
    {id:4, img:"/images/article3.webp", alternative:"/images/vertical7.webp", title:"Pilihan terbaik untuk event meeting anda.", desc:"BBS Rental dalam hal ini sebagai perusahaan penyedia jasa sewa dan rental alat interpreter akan berupaya semaksimal mungkin guna memenuhi kebutuhan pelanggan-pelanggan kami.Terima kasih telah menggunakan jasa kami."},
]

const servicesData = [
    {id:1, img:"/images/vertical4.webp", alternative:"/images/vertical9.webp", title:"Sewa Alat Interpreter", desc:"Dengan kemajuan teknologi yang pesat, hadirnya beragam interpreter system yang canggih semakin memenuhi kebutuhan klien yang kian eksklusif. Sebagai upaya memenuhi harapan klien, kami telah mendapatkan LISENSI DEALER RESMI dari produsen perangkat interpreter system terkemuka dunia. Kini, kami hadir dengan katalog lengkap berisi contoh-contoh alat interpreter terbaru. Klien-klien kami dapat dengan mudah memilih sesuai kebutuhan. Dengan kelengkapan peralatan interpreter system yang dimiliki, kami berkomitmen memberikan yang terbaik. Hubungi kami di +62 877-3561-5623 9 (Phone & Whatsapp) untuk informasi sewa alat interpreter seperti Tour Guide System, Delegate Mic, dan lainnya."},
    {id:2, img:"/images/horizontal3.webp", alternative:"/images/vertical5.webp", title:"Jasa Interpreter Profesional", desc:"Jasa interpreter adalah layanan lain yang kami sediakan bagi klien yang membutuhkan jasa interpreter/penerjemah lisan. Berbeda halnya dengan jasa terjemahan teks (Translation Service), jasa interpreter membutuhkan kefasihan dan kepandaian yang khusus untuk dapat menyampaikan suatu arti secara langsung kepada klien. Untuk itulah, seorang Interpreter harus benar-benar memiliki kecakapan dan juga menguasai semua perbendaharaan kata, agar dalam tugasnya dapat dengan baik dan fasih menyampaikan makna yang sesungguhnya kepada klien. Jasa interpreter kami meliputi semua jenis interpreter bahasa seperti bahasa Inggris, Jepang, Korea, Mandarin, Spanyol, Perancis dan bahasa-bahasa asing lainnya. Jasa interpreter ini terdiri atas 2 jenis, yaitu jasa interpreter biasa dan jasa interpreter tersumpah. Jasa Interpreter Biasa adalah jasa interpreter yang pada umumnya ditujukan untuk keperluan pemandu dalam suatu negosiasi bisnis, pemandu dalam perjalanan wisata dan lain sebagainya. Sedangkan, Jasa Interpreter Tersumpah adalah jasa interpreter/penerjemahan lisan yang khusus ditujukan untuk keperluan yang sangat resmi seperti, dalam suatu exhibition, persidangan di pengadilan, pengajuan klaim ke suatu instansi. Layanan jasa kami sangat bervariasi dan dapat dinegosiasikan sesuai kebutuhan klien. Hingga kini layanan jasa interpreter kami meliputi jasa interpreter untuk bahasa-bahasa asing: Inggris, Jepang, Mandarin, Belanda, Jerman, Korea, Perancis, Arab, Spanyol, Rusia."},
    {id:3, img:"/images/vertical11.webp", alternative:"/images/vertical6.webp", title:"Jasa Penerjemah Tersumpah", desc:"BBS menghadirkan layanan penerjemahan dokumen yang komprehensif dan andal untuk berbagai jenis dokumen, mulai dari dokumen pribadi hingga dokumen korporat atau perusahaan. Proses penerjemahan ini dilakukan secara manual oleh tim penerjemah kami yang berpengalaman dan ahli dalam menerjemahkan dokumen dari berbagai disiplin ilmu. Para staf penerjemah kami sebagian besar telah memperoleh sertifikasi sebagai 'Penerjemah Tersumpah' (Sworn Translator) dengan prestasi kelulusan tertinggi, memastikan keakuratan dan kualitas tinggi dalam setiap penerjemahan. Layanan jasa penerjemah kami mencakup beragam jenis dokumen, seperti Akte Kelahiran, Akte Pernikahan, Akte Perceraian, Akte Kematian, Paspor, Kartu Keluarga, Ijazah, Rapor, Transkrip, Laporan Keuangan, Peraturan Kerja, Anggaran Dasar, Standar Operasional, dan masih banyak lagi. Kami berkomitmen untuk menyediakan solusi penerjemahan yang sesuai dengan kebutuhan Anda dengan ketelitian dan profesionalisme tinggi."},
]

export {portofoliosData, clientsData, articlesData, servicesData}